# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

go2/robot_lab:
  model_name: "policy.pt"
  num_observations: 47
  # phase 2 + ang_vel 3 + gravity 3 + commands 3 + dof_pos 12 + dof_vel 12 + actions 12
  observations: ["phase","ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  
  phase_scale: 3.0
  phase_cycle_period: [0.5, 0.8]  # [min_period, max_period]
  phase_velocity_limit: [0.5, 1.8]  # [stand_threshold, saturation_speed]

  observations_history: [9,8,7,6,5,4,3,2,1,0]  # 0 is the latest observation
  observations_history_priority: "term"  # "time" or "term" priority
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0]
  rl_kp: [20.0, 20.0, 20.0,
          20.0, 20.0, 20.0,
          20.0, 20.0, 20.0,
          20.0, 20.0, 20.0]
  rl_kd: [1.2, 1.2, 1.2,
          1.2, 1.2, 1.2,
          1.2, 1.2, 1.2,
          1.2, 1.2, 1.2]
  fixed_kp: [80.0, 80.0, 80.0,
             80.0, 80.0, 80.0,
             80.0, 80.0, 80.0,
             80.0, 80.0, 80.0]
  fixed_kd: [3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0]
  num_of_dofs: 12
  action_scale: [0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5]
  default_dof_pos: [ 0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
